spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pov
    username: root
    password: root1234
  jpa:
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 3000ms
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id:
            client-secret:
            scope:
              - profile_image
              - email
              - nickname
              - birthday
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucketName: bucket-uplus-127
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  token:
    secretKey: "urecapointofviewsurecapointofviewsurecapoin"

TMDb:
  access:

firebase:
  config:
    path: firebase/firebase-service-account.json

toss:
  secret-key:

oauth:
  baseurl: https://point-of-views.com